// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irfmccimqeigzgqctghe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyZm1jY2ltcWVpZ3pncWN0Z2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDQyNDQsImV4cCI6MjA2MTAyMDI0NH0.63B0kRhMRMG8YVnibZPoFDbXextKFFPkuPgrEc-mWKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);